version: '3.9'
services:
  db:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jwt_node_app
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:4000"
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "${CLIENT_PORT}:3000"